modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/CoolAid48/NoMoreJumpscares/issues"
license = "MIT"

[[mods]]
modId = "nomorejumpscares"
version = "${version}"
displayName = "NoMoreJumpscares"
authors = "CoolAid48"
description = '''
Removes the Elder Guardian curse effect when receiving mining fatigue!
'''
logoFile = "assets/nomorejumpscares/icon.png"

[[mixins]]
config = "nomorejumpscares.mixins.json"
